### ISSUE TITLE
[ENHANCEMENT] 

### ISSUE THREAD

**Issue by aloisDz** [TDRA-ae/aegov-dls#11]
**Is your enhancement request related to a problem? Please describe.**

Users will find difficulties in distinguishing between the selected part and the unselected one

**What are you suggesting as an enhancement**

**Describe alternatives you've considered**
I have attached a screenshot of my perception of the redesign.

you can create more variations of the range slider as well (Ex: a slider with defined steps  0,10, 20, 30 ... 100 ) which can be useful if users have to select specific steps.

![Range Slider Improvement](https://github.com/TDRA-ae/aegov-dls/assets/38811040/ede2dbb2-2446-401d-ac7c-46fa995d5cd1)

**Comment by moiz-conceptlz** [comment]
The range slider - as the default version - will only use the native `<input type="range">` and style it. Hence, the style applied in the design system is for the default browser range.

It is part of the roadmap to include a ranger slider that is JavaScript based. A JavaScript Range Slider will include the ability to have a dual tracker, changes in colour between the tracked section, hover based information on value and more. 

Closing this issue as this would be a new component and not related to the native range.
