### ISSUE TITLE
Alert Component Enhancement 

### ISSUE THREAD

**Issue by aloisDz** [TDRA-ae/aegov-dls#12]
**Is your enhancement request related to a problem? Please describe.**
- I find that the alert component has some visual hierarchy issues due to color usage between the title and body text
- The info alert "lightbulb" icon should be solid as the other states
-  The ( info / warning ) alert titles are uppercase whereas the error is in lowercase

**What are you suggesting as an enhancement**
- Improve visual hierarchy  and overall style through a better usage of color
- improve consistency
![Alerts](https://github.com/TDRA-ae/aegov-dls/assets/38811040/6f54b001-70c4-43d4-ae28-25a30b53b1c4)

**Comment by moiz-conceptlz** [comment]
Version 2.1.0 has been updated which includes changes to the alert component.
