### ISSUE TITLE
[ENHANCEMENT] Global Menu

### ISSUE THREAD

**Issue by aloisDz** [TDRA-ae/aegov-dls#13]
![Group 10122](https://github.com/TDRA-ae/aegov-dls/assets/38811040/6415ea0f-a9ee-46c7-bee8-75bbe26d9096)

**Comment by moiz-conceptlz** [comment]
Dropdown navigations in the design system will not force background colour on links any more. Dropdown menu's will - by default only show the hover state on the menu link. 

It is however allowed to further enhance this functionality and change the background block colour to what is suitable to the design of the dropdown. The barebone version of the navigation element will not include or force a background colour anymore.
