### ISSUE TITLE
Menu in small screens for Arabic content

### ISSUE THREAD

**Issue by moiz-conceptlz** [TDRA-ae/aegov-dls#27]
### Discussed in https://github.com/orgs/TDRA-ae/discussions/25

<div type='discussions-op-text'>

<sup>Originally posted by **ahmedabbous** March  5, 2024</sup>
The menu items on small screens are displayed on two rows which is being reported by many of our clients. Can you please share your feedback on this

![Screenshot 2024-03-05 100316](https://github.com/TDRA-ae/aegov-dls/assets/62495069/0d11532e-f5d6-4673-9bcd-3739b0a48fa8)
</div>

**Comment by moiz-conceptlz** [comment]
Version 2.1.3 addresses this issue and has been released.

**Comment by Manalalafad** [comment]
have a look to this issue again it seems that still apear for some websites !
