### ISSUE TITLE
 The slider block not working in DLS

### ISSUE THREAD

**Issue by Rehan-Alatrash** [TDRA-ae/aegov-dls#41]
**Mention what part of the design system the bug is related to**
 a "Block"

**More context in relation to the design system**
 compiling 

**Describe the bug**
The slider block doesn't have horizontal sliders.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'blocks'
2. Click on 'Slider'
3. Scroll down to 'Variations (Logo slider , Initiatives slide, News slider)'

**Expected behaviour**
The slider block should create a horizontal sliders 

**Screenshots**
![image](https://github.com/TDRA-ae/aegov-dls/assets/72079965/fc5ba36b-da4e-4858-8e49-d1711db59690)

**A bit more context about the browser**
 -  chrome
 - Version 125.0.6422.141

**Is the issue on both Desktop and Smartphones?**
I tested in desktop only

**Comment by moiz-conceptlz** [comment]
Dear @Rehan-Alatrash 

Please see the attached image screenshot for the logo slider function. If you use Slick Slider, you will achieve this as the result.

However, please note that the usage of Slick Slider is not mandatory. You may use any plugin or library that you are comfortable with, as long as the achieved end result is the same. 

Stay tunned as we add more examples of sliders with various other libraries.

<img width="1497" alt="Screenshot 2024-07-04 at 10 55 40 AM" src="https://github.com/TDRA-ae/aegov-dls/assets/7955428/f2e0a1d8-9a13-4c76-89ec-89e02de7c027">
