### ISSUE TITLE
[BUG] Accessibility Implementation Testing

### ISSUE THREAD

**Issue by inowarah** [TDRA-ae/aegov-dls#47]
While using blocks (Footer) , in our project to meet the design system 2.0 and the principles of accessibility first.
https://designsystem.gov.ae/docs/blocks/footer

We did test (Footer) block using WAVE tool , and we get a contrast errors (Very low contrast (4.19:1)) , while the same error appear at the design system portal before adding to our project.

Are we allowed to changed the colors to black for example in order to avoid the issue ?
<img width="1272" alt="image" src="https://github.com/user-attachments/assets/cac6cb0a-e055-4df2-b829-29ac167d0d12">

**Comment by moiz-conceptlz** [comment]
Thank you for raising this issue. This will be fixed in the component and released in version 2.3.4

**Comment by moiz-conceptlz** [comment]
Hello @inowarah 

Version 2.3.4 of the design system was released. 

We are attaching a screenshot of the Footer element using WAVE.

<img width="1475" alt="Screenshot 2024-10-01 at 6 00 42 PM" src="https://github.com/user-attachments/assets/8a2c5e49-5601-43ed-b4e5-1a6952ea22eb">

Thank you for reporting the colour issue. We will be closing this issue now and marking it as resolved.
