### ISSUE TITLE
[Bug] Header Menu Item Hover Effect Not Matching DLS Component

### ISSUE THREAD

**Issue by jamaljaba** [TDRA-ae/aegov-dls#51]
We are in the process of implementing the updated header component. However, after rendering the CSS file, the result does not match the expected behavior of the DLS component. For example, in the DLS component, hovering over a menu item displays the item with a background color, whereas in our implementation, it only underlines the text.

Design System Version: 2.2.4

For reference kindly check attachments.
![imlemented-header-in our-local](https://github.com/user-attachments/assets/c9f7418f-aac6-453d-a562-c8f401b89d87)
![design-sytem-header](https://github.com/user-attachments/assets/73e46343-5f7c-4159-8a38-de857f33e156)

**Comment by moiz-conceptlz** [comment]
Indeed, the background color on the links was part of our initial release.

Feedback from various entities proved that forcing a background color was not a good idea. Hence, we updated the design system component in the plugin to reflect the basic behaviour.

We will updaet the component example itself as well - thank you for sharing this.

I want to take this oppertunity to describe that the dropdown navigation is only a guide. You may choose to add a layout in the dropdown that is most usable towards the number of links and experience you wish to provide.
