### ISSUE TITLE
Creative card font in Arabic not consistent

### ISSUE THREAD

**Issue by moiz-conceptlz** [TDRA-ae/aegov-dls#58]
Creative card is not consider to use the correct font family in the Arabic version, 
currently it show the font: ('Inter', 'Helvetica Neue', ui-sans-serif, system-ui, sans-serif), 
the correct font is: ("Noto Kufi Arabic", ui-sans-serif, "Helvetica Neue", sans-serif)
https://designsystem.gov.ae/docs/components/card
![image](https://github.com/user-attachments/assets/e85d57db-c736-40ca-b6dc-22989bff906a)

_Originally posted by @Mahmoud-87 in https://github.com/TDRA-ae/aegov-dls/discussions/57_

**Comment by Mahmoud-87** [comment]
Please note the same issue already existing also in other 2 components (Mobile App, Newsletter)
![image](https://github.com/user-attachments/assets/bef94cc3-1305-46b6-bd1c-baeba2bd31c1)

**Comment by moiz-conceptlz** [comment]
@Mahmoud-87 

The newsletter is a block. Hence, the code of adding font override in the block is added to the website sample code too. Mobile App banner is not a block, this may have been something you have coded.

So here is how you can override the font.

You will notice that in the class list, there must be `font-inter` added as a class. You simply need to add `rtl:font-alexandria` right after **font-inter** as an additional class. This will help you solve the font issue.

Regarding the creative card - as promised, version 2.2.6 of the design system has solved this along with other minor updates to other components.
