### ISSUE TITLE
[BUG] Background and foreground colors do not have a sufficient contrast ratio

### ISSUE THREAD

**Issue by Sa7aR-Kassem** [TDRA-ae/aegov-dls#66]
Take a moment to review - is it really a bug? Or is it more of an enhancement or a typo in the documentation? A **Bug** is code that is broken, or when you try to implement a certain piece of code that is mentioned in the documentation, you have a result that is not the same as described. 

Now if you are absolutely sure it is indeed a bug, please fill in the following template.

---

**Mention what part of the design system the bug is related to**
Is the bug part of a "Card", a "Button",  a "Anchor" the 

**More context in relation to the design system**
If the bug is part of a component or a block, please mention which one. If the bug is related to the plugin, please mention if it is during installation, compiling or configuration.

**Describe the bug**
A clear and concise description of what the bug is. Help us understand what you are doing that is causing an error.

**To Reproduce**
1. Go to any anchor have the color `aegold-600` & background-color `bg-white`
2. Test accessibility by wave tool or lighthouse chrome tab 
3. Having low contrast color issue

**Expected behavior**
Passing color contrast checking

**Screenshots**
If applicable, add screenshots to help explain your problem. This is not mandatory, but definitely helpful.

**A bit more context about the browser**
 - Browser [e.g. chrome]

**Is the issue on both Desktop and Smartphones?**
Yes on both. Here is where I tested it:

**Additional context**

**Comment by moiz-conceptlz** [comment]
@Sa7aR-Kassem 

Sharing with you a screenshot of the contrast testing tool for `AEGOLD-600` which translates to a hex value of `#92722A` and a background color of white - which translates to `#FFFFFF`

Please confirm if you are using the same hex values and share a screenshot of your your test results that show it as a failed for a AA compatibility.

<img width="1270" alt="Screenshot 2024-11-20 at 10 08 45 AM" src="https://github.com/user-attachments/assets/b45046d6-dad8-4065-ac52-7f49d37d19f6">

**Comment by moiz-conceptlz** [comment]
Closing this, as this is not an issue.

**Comment by moiz-conceptlz** [comment]
Hello @Sa7aR-Kassem 

The screenshot shared by me is also from WebAIM.

I'm also now attaching screenshots from various other tools. But i noticed your background color is not white. In your screenshot, your background color is set to `#f7f7f7` or `rgb(247, 247, 247)`

Surely, if you change the background color, the foreground will cause an issue. 

<img width="1558" alt="Screenshot 2024-11-27 at 2 35 31 PM" src="https://github.com/user-attachments/assets/990c771a-8fe4-45bd-86cb-630aec31a85b">

<img width="1528" alt="Screenshot 2024-11-27 at 2 34 00 PM" src="https://github.com/user-attachments/assets/ddac29fc-193d-4e70-99a5-6d0323f030dd">

<img width="1914" alt="Screenshot 2024-11-27 at 2 33 15 PM" src="https://github.com/user-attachments/assets/681ccb06-5c89-49c5-b21c-ca1fa814240d">

**Comment by Sa7aR-Kassem** [comment]
I reviewed the DLS Figma again and noticed that you are using a background color of `#f7f7f7` with a text color of `#92722A`, as well as a font size smaller than 16px. This results in a contrast issue, which is shown in the following screenshots:

![image](https://github.com/user-attachments/assets/0848fd20-bba6-44d1-970b-ffe4c267bf6d)
![image](https://github.com/user-attachments/assets/1e0265cc-5eec-4236-a875-214d93c95642)

For reference, you can find the relevant section in the Figma design here:
[Design System Figma](https://www.figma.com/design/djLS3gt3zdQ2TBUvfZDegU/aegov-designsystem_2.0?node-id=1406-7026&t=UbjcnJVKwIOgHqAz-0)

I recommend updating the section to use a gray background color. For consistency, I'll apply a card with a white background, and the "View All" button will have a white background, as shown in the screenshot below. Please confirm if this approach works for you.

![image](https://github.com/user-attachments/assets/2947a905-16b6-41aa-b063-939a6c940ccd)

**Comment by Sa7aR-Kassem** [comment]
Hello @moiz-conceptlz ,

Any recommendation dear?
