### ISSUE TITLE
[BUG] Customer Pulse Section on Home Page

### ISSUE THREAD

**Issue by Sa7aR-Kassem** [TDRA-ae/aegov-dls#69]
**Mention what part of the design system the bug is related to**
Missed Component 

**Describe the bug**
I would also appreciate confirmation on placing the "Customer Pulse" and did you find this content useful section directly after the subscription area on the homepage. The goal is to display it consistently across all pages. Does this layout make sense, and is it feasible to implement this structure throughout the site?

**Comment by moiz-conceptlz** [comment]
@Sa7aR-Kassem 

This is not a bug. I request you to open such discussions related to brainstorming or discussions on "how-to" in the "Discussions" tab. 

To answer your question, the https://designsystem.gov.ae/guidelines/actions guideline defines the use of "Floating Action buttons (FAB)". Integrating Customer Pulse is based on the script received by them. If you do not want to place this as a floating button, it is your choice.
