### ISSUE TITLE
[BUG] Load More Button for Comments

### ISSUE THREAD

**Issue by Sa7aR-Kassem** [TDRA-ae/aegov-dls#70]
Mention what part of the design system the bug is related to
Missed Component

Describe the bug
Could you confirm if using a "Load More" button to load the comments section on the blog details page is better than using a pagination component? It seems that this method would provide a more intuitive user experience.

**Comment by moiz-conceptlz** [comment]
@Sa7aR-Kassem 

This is not a bug. I request you to report issues, where there is an issue - such as a component is not reacting the way it is described.

To answer your question - yes, in many cases a "Load more" is useful, and provides a better experience to a user. However, If a user had to share the page URL, after hitting "Load More" 3 times, will the shared URL provide the same content? 

As an experiment try this:

1. Go to the blog page - by default it has 10 posts loaded, and then click on Load More 2 times.
2. On the 2nd time the content is loaded - which means, now there are 30 items on the page. Now, imagine you found something interesting. So you copy the page URL and share it with a friend, saying .. "look what I found on this page"
3. Now imagine, your friend opens the link - but see's only 10 posts loaded

So the point I'm trying to make is .. if you want to implement a "load more", you must add a parameter to the URL that stores the count of items or the total articles loaded, and when such parameter is passed - the page must react to show the same.
