### ISSUE TITLE
[BUG] Issues with Input Date Component in Arabic

### ISSUE THREAD

**Issue by Sa7aR-Kassem** [TDRA-ae/aegov-dls#73]
Description:
We are using your input date component, but I am encountering some issues when using it with Arabic language settings:

**Alignment issues**: The elements are not properly aligned in Arabic.
**Title in English**: The title appears in English instead of Arabic.
**Icon not clickable**: The icon has a cursor pointer.
**Calendar icons:** The calendar icons are not the theme.
Please provide support or an update to resolve these issues.

![image](https://github.com/user-attachments/assets/c45d0ac1-9a35-43b0-b41e-4e32126178ef)
![image](https://github.com/user-attachments/assets/1fec0e28-d757-491c-bea7-192493e03633)

**Comment by moiz-conceptlz** [comment]
Merging this issue with https://github.com/TDRA-ae/aegov-dls/issues/81 

All Date Input related issues to be resolved in Version 2.2.7
