### ISSUE TITLE
[Disccussion] Missed Scroll Component

### ISSUE THREAD

**Issue by Sa7aR-Kassem** [TDRA-ae/aegov-dls#74]
Description
The scroll component is missing, which is essential for the design. I attempted to use the available styling from the DLS portal, but it doesn’t work as expected due to browser compatibility issues.

**Expected behaviour**
There is a scroll component working fine in all browsers with same styling

**Screenshots**
![image](https://github.com/user-attachments/assets/ba4e1ca9-d7b7-443a-b0f3-0eff8b641fe6)
FireFox
![image](https://github.com/user-attachments/assets/8f48423b-d85e-49e5-a1a0-b0300cb2d57b)

**Comment by moiz-conceptlz** [comment]
This is not a bug.

I request you to report a bug, when it affects a component. Changing the scollbar color, width and other elements is a choice. You can refer to https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_scrollbars_styling on how to style a scrollbar.

**Comment by Sa7aR-Kassem** [comment]
I am not asking about the color or width. I am saying that the styles you're using are not compatible with Firefox and other browsers. Therefore, I request that you refer to a scrollbar component that is compatible with all browsers.
