### ISSUE TITLE
[BUG]  Compatibility - Firefox - The input type number field accept characters in the firefox browser

### ISSUE THREAD

**Issue by Sa7aR-Kassem** [TDRA-ae/aegov-dls#82]
When accessing the DLS portal and navigating to the **Input Component** specifically input type number enter non-numeric characters (e.g., "test"). The expected behavior is that the field should not accept characters. However, the field currently allows the characters to be entered, but this issue occurs only in Firefox.

![image](https://github.com/user-attachments/assets/4e518f2c-930f-40a7-88a0-6469e51429de)

![image](https://github.com/user-attachments/assets/012476e4-ca53-4291-90b2-8890fc4601cd)

**Comment by moiz-conceptlz** [comment]
@Sa7aR-Kassem I want to clearly highlight that the design system is not meant to handle JavaScript events. The purpose of the design system is to currently support a consistent style.

It is expected that such things - such as management of key stroke events to disable character input (if required) must be handled by the developer.

Error reporting and validating the input of a user is to be done by the implementing developer.

A JS bundle is provided by the design system that is meant to allow the functionality of the components. It is also mentioned on the website and in the documentation of the design system that using the bundled JS is not mandatory. A developer has the choice to not use the bundled javascript and create their own.

Once again, the purpose of the design system - is to create a consistent design, style and management of JsvaScript events is expected to be managed by the developer.

**Comment by Sa7aR-Kassem** [comment]
@moiz-conceptlz, the explanation is that this is indeed clear, but the goal is compatibility. First, the appearance of the input type is not consistent across browsers. Secondly, the functionality is not unified.

To avoid this issue, we used `<input type="text" />` and implemented validation via JavaScript. We just needed confirmation or other suggestions.
